version: "3.3"

services:
  db:
    image: postgres
    env_file:
      - db_env
  api:
    build: ./online_shop
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./online_shop:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - api_env
